[package]
name = "pg_accel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_pg_accel"
path = "./src/bin/pgrx_embed.rs"

[features]
default = ["pg17", "gpu"]
pg15 = ["pgrx/pg15"]
pg16 = ["pgrx/pg16"]
pg17 = ["pgrx/pg17"]
pg18 = ["pgrx/pg18"]
gpu = []
pg_test = []

[dependencies]
libc = "0.2"
pgrx = "0.17.0"

[dev-dependencies]
pgrx-tests = "0.17.0"

[build-dependencies]

[lints]
workspace = true
